### ISSUE TITLE
toLowerCase is not a function while filtering Customers

### ISSUE THREAD

**Issue by ikismail** [Veilumuthu/driving#1]
https://github.com/Veilumuthu/driving/blob/e211eb4920b71757905d31f9f4fd978d3ff54203/src/components/Customer/CustomerFilter.js#L51

while iterating and checking the condition customer[key] is not a string that's why you dont get string type util functions.

change this line to this.
```
return Object.keys(customer).some((key) => (customer[key] && customer[key]?.toLowerCase().includes(LowercasedCusFilter)))
```

**Comment by Veilumuthu** [comment]
Closed this issue by correcting the code into 

return Object.keys(customer).some((key) => (customer[key] && customer[key]?.toLowerCase().includes(LowercasedCusFilter)))
